Feed
wafflestudio18-5/team6-android pull request #3
Opened 2020-12-25 07:01 UTC by jwg1108

2020-12-25 10:25 UTC, bumkyu00 commented on CarrotMarket/app/src/main/res/layout/item_feed.xml
> +</layout>
제 로컬에서 돌려보니까 <Linear Layout> 등과 같은 실질적인? layout이 없어서 컴파일이 안됩니다. 그래서 직접 넣어서 해보니 Android resource compilation failed 오류가 뜨네요. 혹시 원래는 잘 되나요?

2020-12-25 10:25 UTC, bumkyu00 commented on CarrotMarket/.idea/gradle.xml
> +        <option name="useQualifiedModuleNames" value="true" />
이건 무슨 옵션인지 아시나요? 제 로컬에서 계속 없애려고 그러네요.

2020-12-26 10:01 UTC, jwg1108 commented on CarrotMarket/.idea/gradle.xml
> +        <option name="useQualifiedModuleNames" value="true" />
이건 잘 모르겠네요..

2020-12-27 08:05 UTC, bumkyu00 commented
conflict 문제되는 건 없어보여서 전부 resolve 했습니다.
다만 implementation 'com.android.support:design:26.1.0' 요거는 제가 알기로 androidx로 바꾸는 게 좋을 것 같습니다.

2020-12-28 12:36 UTC, jwg1108 commented
> conflict 문제되는 건 없어보여서 전부 resolve 했습니다.
> 다만 implementation 'com.android.support:design:26.1.0' 요거는 제가 알기로 androidx로 바꾸는 게 좋을 것 같습니다.

알겠습니다. login activity 부분은 구현하신거같아서 이 브랜치에서는 우선 삭제할게요. 그리고 이 브랜치는 백엔드 연결되면 추가로 수정해서 다시 pr할게요

2020-12-28 13:26 UTC, bumkyu00 commented
아 login activity 만들어놓으셨네요
굳이 삭제할 필요까지는 없을거같아요ㅎㅎ 제가 따로 안 만들어놓기도 했고

2021-01-04 12:17 UTC, sanggggg requested changes
엥? 이거 제가 리뷰 submit 버튼을 안눌러서 한참동안 리뷰 없는 상태로 남아있었네요 ㅋㅋㅋㅋㅋㅋ

2021-01-04 12:17 UTC, sanggggg commented on CarrotMarket/app/src/main/java/com/example/carrotmarket/api/Service.kt
> +    fun getfeed(): Observable<List<Feed>>
네트워크는 한번 받아오면 끝이여서 Observable 말고 Single 을 사용하는게 좋을 것 같습니다.

2021-01-04 12:17 UTC, sanggggg commented on CarrotMarket/app/src/main/java/com/example/carrotmarket/api/Service.kt
> +)
Dto 는 따로 파일을 분리해서 관리합시다

2021-01-04 12:17 UTC, sanggggg commented on CarrotMarket/app/src/main/java/com/example/carrotmarket/ui/feed/DetailFeedViewModel.kt
> +class DetailFeedViewModel(private val repository: Repository):ViewModel() {
[nitpick]
띄워쓰기를 보니 군데군데 파일 포매팅을 안돌린 것 같습니다

2021-01-06 13:30 UTC, sanggggg requested changes

2021-01-06 13:30 UTC, sanggggg commented on CarrotMarket/app/build.gradle
>          versionName "1.0"
구두로 리뷰 전달함

2021-01-07 12:43 UTC, sanggggg approved these changes

2021-01-07 13:25 UTC, merged