카카오 로그인
wafflestudio18-5/team6-android pull request #4
Opened 2020-12-28 10:16 UTC by bumkyu00

로그인 버튼: 토큰 가져오기
로그아웃 버튼: 토큰 삭제

2020-12-28 12:33 UTC, jwg1108 reviewed
제가 보기에는 크게 문제가 없어보이긴 하는데... 로그인을 home fragment에서 하기보다는 login activity를 따로 만들어서 로그인한 후 로그인이 되면 mainactivity로 이동해야 하지 않을까요?

2020-12-28 13:20 UTC, bumkyu00 commented
네 맞습니다ㅎㅎ
내일 모이기로 한 것도 있고 해서 우선 보여주기 식?으로 해논거고 옮겨야겠죠. 이식은 그렇게 안 어려울거 같네요

2021-01-06 13:33 UTC, sanggggg commented on CarrotMarket/app/src/main/java/com/example/carrotmarket/ui/HomeFragment.kt
> +                        Log.d("tag", "로그인 실패", error)
https://github.com/JakeWharton/timber
팀버 사용 추천!

2021-01-06 13:36 UTC, sanggggg requested changes

2021-01-06 13:36 UTC, sanggggg commented on CarrotMarket/app/src/main/java/com/example/carrotmarket/CarrotMarketApplication.kt
> +        KakaoSdk.init(this, "a491f4206056cafb222c1b9c67a3b9d0")
local.properties? 로 시크릿 키를 빼는게 좋을 것 같습니다.
또는  secrets.xml 을 따로 파서 거기 레포에 남겨지면 안되는 리소스들을 적고 gitignore 로 제외시키는게 좋아보입니다.

2021-01-07 13:34 UTC, merged